services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - server
    networks:
      - streaming_network
