version: '3.8'

networks:
  streaming_network:
    driver: bridge

services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - streaming_network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - streaming_network

  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      KAFKA_BROKER: kafka:9092
      MONGO_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - kafka
      - mongo
    networks:
      - streaming_network

  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/usr/src/app
  #     - /usr/src/app/node_modules
  #   environment:
  #     NODE_ENV: development
  #   depends_on:
  #     - server
  #   networks:
  #     - streaming_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - streaming_network

volumes:
  mongo_data:
