# Build stage
FROM node:18 AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Production stage
FROM node:18-slim

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app .

EXPOSE 4000

CMD ["node", "index.js"]
